// Generated by tools/collate/gen.py from ICU 76.1's root collation and
// its tailorings; do not edit. Layout and meaning: collate.rs.

/// The chunks the root collation's entries are cut into, by number.
pub const CHUNKS: [&str; 12] = [
    "latin",
    "greek",
    "cyrillic",
    "middle-east",
    "indic",
    "southeast-asia",
    "east-asia",
    "han",
    "han-ext",
    "symbols",
    "other",
    "smp",
];

/// The ranges of code points each chunk holds, ascending. Past them a
/// code point of the Basic Multilingual Plane is `other`'s and one of the
/// Supplementary Multilingual Plane `smp`'s.
pub(super) const BLOCKS: [(u32, u32, u8); 44] = [
    (0x0000, 0x0370, 0),
    (0x0370, 0x0400, 1),
    (0x0400, 0x0530, 2),
    (0x0530, 0x0900, 3),
    (0x0900, 0x0E00, 4),
    (0x0E00, 0x1000, 5),
    (0x1000, 0x10A0, 5),
    (0x1100, 0x1200, 6),
    (0x1780, 0x1800, 5),
    (0x1950, 0x1AB0, 5),
    (0x1B00, 0x1C80, 5),
    (0x1C80, 0x1C90, 2),
    (0x1CD0, 0x1D00, 4),
    (0x1E00, 0x1F00, 0),
    (0x1F00, 0x2000, 1),
    (0x2000, 0x2190, 0),
    (0x2190, 0x2C00, 9),
    (0x2C60, 0x2C80, 0),
    (0x2DE0, 0x2E00, 2),
    (0x2E00, 0x2E80, 9),
    (0x2E80, 0x3400, 6),
    (0x3400, 0xA000, 7),
    (0xA000, 0xA4D0, 6),
    (0xA640, 0xA6A0, 2),
    (0xA830, 0xA840, 4),
    (0xA8E0, 0xA900, 4),
    (0xA900, 0xAB00, 5),
    (0xA960, 0xA980, 6),
    (0xABC0, 0xAC00, 5),
    (0xD7B0, 0xD800, 6),
    (0xF900, 0xFB00, 7),
    (0xFB00, 0xFB07, 0),
    (0xFB13, 0xFB18, 3),
    (0xFB1D, 0xFE00, 3),
    (0xFE00, 0xFE10, 0),
    (0xFE30, 0xFE50, 6),
    (0xFE70, 0xFEFF, 3),
    (0xFEFF, 0xFF00, 0),
    (0xFF00, 0xFFF0, 6),
    (0xFFF0, 0x10000, 0),
    (0x1D000, 0x1D800, 9),
    (0x1F000, 0x1FC00, 9),
    (0x20000, 0x40000, 8),
    (0xE0000, 0xE1000, 9),
];
pub(super) const OTHER: usize = 10;
pub(super) const SMP: usize = 11;

/// The characters that can be the second or third of characters sorting
/// as one -- and a few beside them -- as half-open ranges.
pub(super) const CONTINUES: [(u32, u32); 27] = [
    (0x00B7, 0x00B8),
    (0x0306, 0x0345),
    (0x0387, 0x0388),
    (0x0653, 0x0656),
    (0x09BE, 0x09D8),
    (0x0B3E, 0x0B58),
    (0x0BBE, 0x0BD8),
    (0x0C56, 0x0C57),
    (0x0CC2, 0x0CD7),
    (0x0D3E, 0x0D58),
    (0x0DCA, 0x0DE0),
    (0x0E01, 0x0E33),
    (0x0E81, 0x0EB3),
    (0x0EDC, 0x0EE0),
    (0x0F71, 0x0F82),
    (0x102E, 0x102F),
    (0x1980, 0x19AC),
    (0x1B35, 0x1B36),
    (0xAA80, 0xAAB0),
    (0x11127, 0x11128),
    (0x1133E, 0x11358),
    (0x113B8, 0x113CA),
    (0x114B0, 0x114BE),
    (0x115AF, 0x115B0),
    (0x11930, 0x11931),
    (0x1611E, 0x1612A),
    (0x16D67, 0x16D69),
];

/// The tailorings, by number.
pub(super) const TAILORINGS: [&str; 1] = ["tr"];

/// Every chunk's bytes the build carries: all of them natively, `latin`
/// alone in the browser module, which is handed the rest as a page
/// needs them.
#[cfg(not(target_arch = "wasm32"))]
pub(super) static EMBEDDED: [&[u8]; 12] = [
    include_bytes!("latin.bin"),
    include_bytes!("greek.bin"),
    include_bytes!("cyrillic.bin"),
    include_bytes!("middle-east.bin"),
    include_bytes!("indic.bin"),
    include_bytes!("southeast-asia.bin"),
    include_bytes!("east-asia.bin"),
    include_bytes!("han.bin"),
    include_bytes!("han-ext.bin"),
    include_bytes!("symbols.bin"),
    include_bytes!("other.bin"),
    include_bytes!("smp.bin"),
];
#[cfg(target_arch = "wasm32")]
pub(super) static EMBEDDED: [&[u8]; 12] = [
    include_bytes!("latin.bin"),
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
    &[],
];

/// The tailorings' bytes, which every build carries.
pub(super) static TAILORED: [&[u8]; 1] = [include_bytes!("tr.bin")];

/// What every chunk and tailoring of these tables carries.
pub(super) const STAMP: u32 = 0x59708C4D;

/// Where ICU puts an unassigned or private code point, by code point.
pub(super) const IMPLICIT: u32 = 24929;
/// The secondary and tertiary ranks of a letter without an accent, in
/// lowercase.
pub(super) const COMMON_S: u32 = 1;
pub(super) const COMMON_T: u32 = 2;
