[package]
name = "fenec-pg"
description = "PostgreSQL plugin for fenecdb: a v3 wire protocol server"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
fenec-core.workspace = true
fenec-ql.workspace = true
fenec-http.workspace = true
fenec-catalog.workspace = true

[[bin]]
name = "fenec-pg"
path = "src/main.rs"
