// web/fenec.d.ts held to web/fenec.js: `make types-check`. Every name the
// module exports and every method its classes carry is touched from a
// TypeScript file generated here, so one the declarations leave out fails
// the check; usage.ts is what a caller writes, and what the types must
// refuse. tsc runs over both under --strict.
//
// The declarations are written by hand beside a module with no build step,
// and nothing held them to it: a Worker's compiled module was taken by
// `open` and not by its type, and FenecSync's write and start were public
// and undeclared.

import { execFileSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import * as fenec from '../fenec.js';

// Public by necessity, not by intent: called across classes of the module,
// so they cannot be `#private`.
const INTERNAL = {
  FenecSync: {
    write: 'the builder bound to a replica writes through it (`Query.insert` and the rest)',
    start: '`sync()` starts the replica it made with it',
  },
};

const isClass = (v) => typeof v === 'function' && /^class\b/.test(Function.prototype.toString.call(v));
const names = Object.keys(fenec).sort();
const out = [
  '// Generated by check.mjs: every export and method of fenec.js, touched.',
  `import { ${names.join(', ')} } from '../fenec.js';`,
  `void [${names.join(', ')}];`,
];
for (const name of names) {
  const value = fenec[name];
  if (!isClass(value)) continue;
  const skip = INTERNAL[name] ?? {};
  for (const key of Object.getOwnPropertyNames(value)) {
    if (['length', 'name', 'prototype'].includes(key) || key in skip) continue;
    out.push(`void ${name}.${key};`);
  }
  const generic = value.length >= 0 && name !== 'FenecError' ? '<any>' : '';
  out.push(`declare const a${name}: ${name}${generic};`);
  for (const key of Object.getOwnPropertyNames(value.prototype)) {
    if (key === 'constructor' || key in skip) continue;
    out.push(`void a${name}.${key};`);
  }
}
const here = new URL('.', import.meta.url).pathname;
writeFileSync(`${here}probe.ts`, `${out.join('\n')}\n`);
try {
  execFileSync(
    `${here}node_modules/.bin/tsc`,
    ['--noEmit', '--strict', '--target', 'es2022', '--module', 'nodenext', '--moduleResolution', 'nodenext', '--lib', 'es2022,dom', 'usage.ts', 'probe.ts'],
    { cwd: here, stdio: 'inherit' },
  );
} catch {
  process.exit(1);
}
console.log(`fenec.d.ts: ${names.length} exports and their methods declared; usage.ts checks`);
