// web/fenec.d.ts held to web/fenec.js: `make types-check`. Every name the
// module exports and every method its classes carry is touched from a
// TypeScript file generated here, so one the declarations leave out fails
// the check; usage.ts is what a caller writes, and what the types must
// refuse. tsc runs over both under --strict.
//
// The declarations are written by hand beside a module with no build step,
// and nothing held them to it: a Worker's compiled module was taken by
// `open` and not by its type, and FenecSync's write and start were public
// and undeclared.

import { execFileSync } from 'node:child_process';
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import * as fenec from '../fenec.js';

// schema.ts holds tables declared in code to the types `fenec types`
// generates for the same collections: `--schema` makes the file from the
// tables (schema-tables.ts) and writes what `fenec types` reads out of it
// (schema-generated.d.ts), with target/debug/fenec or FENEC=<binary>.
// web/fenec.schema.test.js makes it again and fails when it differs.
if (process.argv.includes('--schema')) {
  const here = new URL('.', import.meta.url).pathname;
  const bin = process.env.FENEC ?? join(here, '../../target/debug/fenec');
  const { tables } = await import('./schema-tables.ts');
  const db = await fenec.Fenec.open(readFileSync(join(here, '../fenec.wasm')), { schema: tables });
  const dir = mkdtempSync(join(tmpdir(), 'fenec-types-'));
  try {
    writeFileSync(join(dir, 'tables.fenec'), db.snapshot());
    const types = execFileSync(bin, ['types', 'tables.fenec'], { cwd: dir, encoding: 'utf8' });
    writeFileSync(join(here, 'schema-generated.d.ts'), types);
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

// Public by necessity, not by intent: called across classes of the module,
// so they cannot be `#private`.
const INTERNAL = {
  FenecSync: {
    write: 'the builder bound to a replica writes through it (`Query.insert` and the rest)',
    start: '`sync()` starts the replica it made with it',
  },
};

const isClass = (v) => typeof v === 'function' && /^class\b/.test(Function.prototype.toString.call(v));
const names = Object.keys(fenec).sort();
const out = [
  '// Generated by check.mjs: every export and method of fenec.js, touched.',
  `import { ${names.join(', ')} } from '../fenec.js';`,
  `void [${names.join(', ')}];`,
];
for (const name of names) {
  const value = fenec[name];
  if (!isClass(value)) continue;
  const skip = INTERNAL[name] ?? {};
  for (const key of Object.getOwnPropertyNames(value)) {
    if (['length', 'name', 'prototype'].includes(key) || key in skip) continue;
    out.push(`void ${name}.${key};`);
  }
  const generic = value.length >= 0 && name !== 'FenecError' ? '<any>' : '';
  out.push(`declare const a${name}: ${name}${generic};`);
  for (const key of Object.getOwnPropertyNames(value.prototype)) {
    if (key === 'constructor' || key in skip) continue;
    out.push(`void a${name}.${key};`);
  }
}
// And schema.js's: every builder it exports, declared.
const schemaNames = Object.keys(await import('../schema.js')).sort();
out.push(`import { ${schemaNames.join(', ')} } from '../schema.js';`, `void [${schemaNames.join(', ')}];`);
const here = new URL('.', import.meta.url).pathname;
writeFileSync(`${here}probe.ts`, `${out.join('\n')}\n`);
// A tsconfig of its own, for React's types: schema.ts holds `useLiveQuery`
// to the rows a query is typed with, and integrations/react imports 'react'.
writeFileSync(
  `${here}tsconfig.check.json`,
  `${JSON.stringify(
    {
      compilerOptions: {
        noEmit: true,
        strict: true,
        target: 'es2022',
        module: 'nodenext',
        moduleResolution: 'nodenext',
        lib: ['es2022', 'dom'],
        allowImportingTsExtensions: true,
        types: [],
        paths: { react: ['./node_modules/@types/react/index.d.ts'] },
      },
      files: ['usage.ts', 'schema.ts', 'probe.ts'],
    },
    null,
    2,
  )}\n`,
);
try {
  execFileSync(`${here}node_modules/.bin/tsc`, ['-p', 'tsconfig.check.json'], { cwd: here, stdio: 'inherit' });
} catch {
  process.exit(1);
}
console.log(
  `fenec.d.ts: ${names.length} exports and their methods declared, schema.d.ts ${schemaNames.length}; usage.ts and schema.ts check`,
);
